services:
  django:
    build: .
    image: django
    container_name: django_jwt_auth
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    image: postgres:17.0-alpine3.20
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:
